server:
  port: 8084

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:mysql://localhost:3306/review_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  services:
    user: http://localhost:8081
    hotel: http://localhost:8082
    reservation: http://localhost:8083

logging:
  level:
    com.hotelchain.reviewservice: DEBUG